name: Library compatibility check

on:
  workflow_call:

jobs:
  lib-compatibility-check:
    name: Library compatibility check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        angular-version: [ 19,20 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Override Angular version ${{ matrix.angular-version }}
        run: |
          pnpm add --force \
            @angular/common@${{ matrix.angular-version }} \
            @angular/core@${{ matrix.angular-version }}

      - name: Build
        run: pnpm nx build ngx-easy-view-transitions --configuration=production
